spring:
  profiles:
    active: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070
---
spring:
  profiles: dev
  datasource:
    url: "jdbc:postgresql://192.168.99.100:5432/postgres"
---
spring:
  profiles: prod
  datasource:
      url: "jdbc:postgresql://database:5432/postgres"

