version: "3"
services:

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  database:
    networks:
      - backend
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]

  fiboworker:
    networks:
      - backend
    image: troofy/fibo-worker
    ports:
      - "8070:8070"
    depends_on:
      - database
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]

  face:
    networks:
      - backend
    image: troofy/fibo-master
    depends_on:
      - database
      - fiboworker
    ports:
      - "8090:8090"
    deploy:
      placement:
        constraints: [node.role == worker]

  



networks:
  backend:

volumes:
  postgres-data:

